# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fiber-annotation` gem.
# Please instead update this file by running `bin/tapioca gem fiber-annotation`.


# Released under the MIT License.
# Copyright, 2023, by Samuel Williams.
#
# pkg:gem/fiber-annotation#lib/fiber/annotation.rb:8
class Fiber
  include ::Fiber::Annotation

  # pkg:gem/fiber-annotation#lib/fiber/annotation.rb:13
  def initialize(annotation: T.unsafe(nil), **options, &block); end

  class << self
    # @scope Fiber
    # @name self.annotate
    # Annotate the current fiber with the given annotation.
    #
    # pkg:gem/fiber-annotation#lib/fiber/annotation.rb:55
    def annotate(*, **, &); end
  end
end

# A mechanism for annotating fibers.
#
# pkg:gem/fiber-annotation#lib/fiber/annotation.rb:10
module Fiber::Annotation
  # Annotate the current fiber with the given annotation.
  # @parameter annotation [Object] The annotation to set.
  #
  # pkg:gem/fiber-annotation#lib/fiber/annotation.rb:13
  def initialize(annotation: T.unsafe(nil), **options, &block); end

  # Annotate the current fiber with the given annotation.
  #
  # If a block is given, the annotation is set for the duration of the block and then restored to the previous value.
  #
  # The block form of this method should only be invoked on the current fiber.
  #
  # @parameter annotation [Object] The annotation to set.
  # @yields {} The block to execute with the given annotation.
  # @returns [Object] The return value of the block.
  #
  # pkg:gem/fiber-annotation#lib/fiber/annotation.rb:31
  def annotate(annotation); end

  # Get the current annotation.
  # @returns [Object] The current annotation.
  #
  # pkg:gem/fiber-annotation#lib/fiber/annotation.rb:20
  def annotation; end

  # Get the current annotation.
  # @returns [Object] The current annotation.
  #
  # pkg:gem/fiber-annotation#lib/fiber/annotation.rb:20
  def annotation=(_arg0); end
end
