# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `msgpack` gem.
# Please instead update this file by running `bin/tapioca gem msgpack`.


# pkg:gem/msgpack#lib/msgpack/core_ext.rb:67
class Array
  include ::Enumerable
  include ::MessagePack::CoreExt

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:71
  def to_msgpack_with_packer(packer); end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:37
class FalseClass
  include ::MessagePack::CoreExt

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:41
  def to_msgpack_with_packer(packer); end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:47
class Float < ::Numeric
  include ::MessagePack::CoreExt

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:51
  def to_msgpack_with_packer(packer); end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:77
class Hash
  include ::Enumerable
  include ::MessagePack::CoreExt

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:81
  def to_msgpack_with_packer(packer); end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:98
class Integer < ::Numeric
  include ::MessagePack::CoreExt

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:102
  def to_msgpack_with_packer(packer); end
end

Integer::GMP_VERSION = T.let(T.unsafe(nil), String)

# MessagePack extention packer and unpacker for built-in Time class
#
# pkg:gem/msgpack#lib/msgpack/version.rb:1
module MessagePack
  private

  # pkg:gem/msgpack#lib/msgpack.rb:44
  def dump(v, io = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack.rb:22
  def load(src, param = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack.rb:39
  def pack(v, io = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack.rb:34
  def unpack(src, param = T.unsafe(nil)); end

  class << self
    # pkg:gem/msgpack#lib/msgpack.rb:47
    def dump(v, io = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/msgpack#lib/msgpack.rb:36
    def load(src, param = T.unsafe(nil)); end

    # pkg:gem/msgpack#lib/msgpack.rb:46
    def pack(v, io = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/msgpack#lib/msgpack.rb:37
    def unpack(src, param = T.unsafe(nil)); end
  end
end

# pkg:gem/msgpack#lib/msgpack.rb:7
class MessagePack::Buffer
  # pkg:gem/msgpack#lib/msgpack.rb:7
  def initialize(*_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def <<(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def clear; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def close; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def empty?; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def flush; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def io; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def read(*_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def read_all(*_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def size; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def skip(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def skip_all(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def to_a; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def to_s; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def to_str; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_to(_arg0); end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:2
module MessagePack::CoreExt
  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:3
  def to_msgpack(packer_or_io = T.unsafe(nil)); end
end

# pkg:gem/msgpack#lib/msgpack.rb:7
class MessagePack::ExtensionValue < ::Struct
  include ::MessagePack::CoreExt

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def payload; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def payload=(_); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def type; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def type=(_); end

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:134
  def to_msgpack_with_packer(packer); end

  class << self
    # pkg:gem/msgpack#lib/msgpack.rb:7
    def [](*_arg0); end

    # pkg:gem/msgpack#lib/msgpack.rb:7
    def inspect; end

    # pkg:gem/msgpack#lib/msgpack.rb:7
    def keyword_init?; end

    # pkg:gem/msgpack#lib/msgpack.rb:7
    def members; end

    # pkg:gem/msgpack#lib/msgpack.rb:7
    def new(*_arg0); end
  end
end

# pkg:gem/msgpack#lib/msgpack.rb:7
class MessagePack::Factory
  # pkg:gem/msgpack#lib/msgpack.rb:7
  def initialize(*_arg0); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:117
  def dump(v, *rest); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def dup; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def freeze; end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:103
  def load(src, param = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:122
  def pack(v, *rest); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def packer(*_arg0); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:124
  def pool(size = T.unsafe(nil), **options); end

  # see ext for other methods
  #
  # pkg:gem/msgpack#lib/msgpack/factory.rb:5
  def register_type(type, klass, options = T.unsafe(nil)); end

  # [ {type: id, class: Class(or nil), packer: arg, unpacker: arg}, ... ]
  #
  # pkg:gem/msgpack#lib/msgpack/factory.rb:45
  def registered_types(selector = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:90
  def type_registered?(klass_or_type, selector = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:115
  def unpack(src, param = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def unpacker(*_arg0); end

  private

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def register_type_internal(_arg0, _arg1, _arg2); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def registered_types_internal; end
end

# pkg:gem/msgpack#lib/msgpack/factory.rb:132
class MessagePack::Factory::Pool
  # pkg:gem/msgpack#lib/msgpack/factory.rb:185
  def initialize(factory, size, options = T.unsafe(nil)); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:199
  def dump(object); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:192
  def load(data); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:210
  def packer(&block); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:206
  def unpacker(&block); end
end

# pkg:gem/msgpack#lib/msgpack/factory.rb:134
class MessagePack::Factory::Pool::MemberPool
  # pkg:gem/msgpack#lib/msgpack/factory.rb:135
  def initialize(size, &block); end

  # pkg:gem/msgpack#lib/msgpack/factory.rb:141
  def with; end
end

# pkg:gem/msgpack#lib/msgpack.rb:7
class MessagePack::HeldBuffer < ::BasicObject; end

# pkg:gem/msgpack#lib/msgpack.rb:7
class MessagePack::Packer
  # pkg:gem/msgpack#lib/msgpack.rb:7
  def initialize(*_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def buffer; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def clear; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def compatibility_mode?; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def empty?; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def flush; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def full_pack; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def pack(_arg0); end

  # pkg:gem/msgpack#lib/msgpack/packer.rb:9
  def register_type(type, klass, method_name = T.unsafe(nil), &block); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def register_type_internal(_arg0, _arg1, _arg2); end

  # pkg:gem/msgpack#lib/msgpack/packer.rb:14
  def registered_types; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def reset; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def size; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def to_a; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def to_s; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def to_str; end

  # pkg:gem/msgpack#lib/msgpack/packer.rb:24
  def type_registered?(klass_or_type); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_array(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_array_header(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_bin(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_bin_header(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_ext(_arg0, _arg1); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_extension(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_false; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_float(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_float32(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_hash(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_int(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_map_header(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_nil; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_string(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_symbol(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_to(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def write_true; end

  private

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def registered_types_internal; end
end

# pkg:gem/msgpack#lib/msgpack/time.rb:5
module MessagePack::Time; end

# pkg:gem/msgpack#lib/msgpack/time.rb:25
MessagePack::Time::Packer = T.let(T.unsafe(nil), Proc)

# 3-arg Time.at is available Ruby >= 2.5
#
# pkg:gem/msgpack#lib/msgpack/time.rb:7
MessagePack::Time::TIME_AT_3_AVAILABLE = T.let(T.unsafe(nil), TrueClass)

# pkg:gem/msgpack#lib/msgpack/time.rb:13
MessagePack::Time::Unpacker = T.let(T.unsafe(nil), Proc)

# pkg:gem/msgpack#lib/msgpack/timestamp.rb:4
class MessagePack::Timestamp
  # @param [Integer] sec
  # @param [Integer] nsec
  #
  # pkg:gem/msgpack#lib/msgpack/timestamp.rb:24
  def initialize(sec, nsec); end

  # pkg:gem/msgpack#lib/msgpack/timestamp.rb:72
  def ==(other); end

  # @return [Integer]
  #
  # pkg:gem/msgpack#lib/msgpack/timestamp.rb:20
  def nsec; end

  # @return [Integer]
  #
  # pkg:gem/msgpack#lib/msgpack/timestamp.rb:17
  def sec; end

  # pkg:gem/msgpack#lib/msgpack/timestamp.rb:68
  def to_msgpack_ext; end

  class << self
    # pkg:gem/msgpack#lib/msgpack/timestamp.rb:29
    def from_msgpack_ext(data); end

    # pkg:gem/msgpack#lib/msgpack/timestamp.rb:50
    def to_msgpack_ext(sec, nsec); end
  end
end

# pkg:gem/msgpack#lib/msgpack/timestamp.rb:13
MessagePack::Timestamp::TIMESTAMP32_MAX_SEC = T.let(T.unsafe(nil), Integer)

# pkg:gem/msgpack#lib/msgpack/timestamp.rb:14
MessagePack::Timestamp::TIMESTAMP64_MAX_SEC = T.let(T.unsafe(nil), Integer)

# The timestamp extension type defined in the MessagePack spec.
# See https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type for details.
#
# pkg:gem/msgpack#lib/msgpack/timestamp.rb:11
MessagePack::Timestamp::TYPE = T.let(T.unsafe(nil), Integer)

# pkg:gem/msgpack#lib/msgpack.rb:7
class MessagePack::UnexpectedTypeError < ::MessagePack::UnpackError
  include ::MessagePack::TypeError
end

# pkg:gem/msgpack#lib/msgpack.rb:7
class MessagePack::Unpacker
  # pkg:gem/msgpack#lib/msgpack.rb:7
  def initialize(*_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def allow_unknown_ext?; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def buffer; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def each; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def feed(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def feed_each(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def feed_reference(_arg0); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def freeze?; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def full_unpack; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def read; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def read_array_header; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def read_map_header; end

  # pkg:gem/msgpack#lib/msgpack/unpacker.rb:9
  def register_type(type, klass = T.unsafe(nil), method_name = T.unsafe(nil), &block); end

  # pkg:gem/msgpack#lib/msgpack/unpacker.rb:18
  def registered_types; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def reset; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def skip; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def skip_nil; end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def symbolize_keys?; end

  # pkg:gem/msgpack#lib/msgpack/unpacker.rb:28
  def type_registered?(klass_or_type); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def unpack; end

  private

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def register_type_internal(_arg0, _arg1, _arg2); end

  # pkg:gem/msgpack#lib/msgpack.rb:7
  def registered_types_internal; end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:17
class NilClass
  include ::MessagePack::CoreExt
  include ::BSON::Specialized

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:21
  def to_msgpack_with_packer(packer); end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:57
class String
  include ::Comparable
  include ::MessagePack::CoreExt

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:61
  def to_msgpack_with_packer(packer); end
end

# pkg:gem/msgpack#lib/msgpack/symbol.rb:1
class Symbol
  include ::Comparable
  include ::MessagePack::CoreExt

  # pkg:gem/msgpack#lib/msgpack/symbol.rb:7
  def to_msgpack_ext; end

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:91
  def to_msgpack_with_packer(packer); end

  class << self
    # pkg:gem/msgpack#lib/msgpack/symbol.rb:12
    def from_msgpack_ext(data); end
  end
end

# pkg:gem/msgpack#lib/msgpack/core_ext.rb:27
class TrueClass
  include ::MessagePack::CoreExt

  private

  # pkg:gem/msgpack#lib/msgpack/core_ext.rb:31
  def to_msgpack_with_packer(packer); end
end
