# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `redis-client` gem.
# Please instead update this file by running `bin/tapioca gem redis-client`.


module Process
  extend ::SQLite3::ForkSafety::CoreExt
  extend ::RedisClient::PIDCache::CoreExt
  extend ::ConnectionPool::ForkTracker
  extend ::ActiveSupport::ForkTracker::CoreExt
end

# pkg:gem/redis-client#lib/redis_client/version.rb:3
class RedisClient
  include ::RedisClient::Common

  # pkg:gem/redis-client#lib/redis_client.rb:269
  def initialize(config, **); end

  # pkg:gem/redis-client#lib/redis_client.rb:421
  def blocking_call(timeout, *command, **kwargs); end

  # pkg:gem/redis-client#lib/redis_client.rb:441
  def blocking_call_v(timeout, command); end

  # pkg:gem/redis-client#lib/redis_client.rb:361
  def call(*command, **kwargs); end

  # pkg:gem/redis-client#lib/redis_client.rb:391
  def call_once(*command, **kwargs); end

  # pkg:gem/redis-client#lib/redis_client.rb:406
  def call_once_v(command); end

  # pkg:gem/redis-client#lib/redis_client.rb:376
  def call_v(command); end

  # pkg:gem/redis-client#lib/redis_client.rb:501
  def close; end

  # pkg:gem/redis-client#lib/redis_client.rb:497
  def connected?; end

  # pkg:gem/redis-client#lib/redis_client.rb:298
  def db; end

  # pkg:gem/redis-client#lib/redis_client.rb:506
  def disable_reconnection(&block); end

  # pkg:gem/redis-client#lib/redis_client.rb:302
  def host; end

  # pkg:gem/redis-client#lib/redis_client.rb:479
  def hscan(key, *args, **kwargs, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:286
  def id; end

  # pkg:gem/redis-client#lib/redis_client.rb:294
  def idle_timeout; end

  # pkg:gem/redis-client#lib/redis_client.rb:277
  def inspect; end

  # pkg:gem/redis-client#lib/redis_client.rb:353
  def measure_round_trip_delay; end

  # pkg:gem/redis-client#lib/redis_client.rb:528
  def multi(watch: T.unsafe(nil), &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:318
  def password; end

  # pkg:gem/redis-client#lib/redis_client.rb:310
  def path; end

  # pkg:gem/redis-client#lib/redis_client.rb:510
  def pipelined(exception: T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client.rb:306
  def port; end

  # pkg:gem/redis-client#lib/redis_client.rb:347
  def pubsub; end

  # pkg:gem/redis-client#lib/redis_client.rb:337
  def read_timeout=(timeout); end

  # pkg:gem/redis-client#lib/redis_client.rb:461
  def scan(*args, **kwargs, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:282
  def server_url; end

  # pkg:gem/redis-client#lib/redis_client.rb:322
  def size; end

  # pkg:gem/redis-client#lib/redis_client.rb:470
  def sscan(key, *args, **kwargs, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:329
  def then(_options = T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client.rb:290
  def timeout; end

  # pkg:gem/redis-client#lib/redis_client.rb:331
  def timeout=(timeout); end

  # pkg:gem/redis-client#lib/redis_client.rb:314
  def username; end

  # pkg:gem/redis-client#lib/redis_client.rb:326
  def with(_options = T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client.rb:342
  def write_timeout=(timeout); end

  # pkg:gem/redis-client#lib/redis_client.rb:488
  def zscan(key, *args, **kwargs, &block); end

  private

  # pkg:gem/redis-client#lib/redis_client.rb:735
  def build_transaction; end

  # pkg:gem/redis-client#lib/redis_client.rb:846
  def connect; end

  # pkg:gem/redis-client#lib/redis_client.rb:769
  def ensure_connected(retryable: T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client.rb:828
  def raw_connection; end

  # pkg:gem/redis-client#lib/redis_client.rb:743
  def scan_list(cursor_index, command, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:753
  def scan_pairs(cursor_index, command); end

  class << self
    # pkg:gem/redis-client#lib/redis_client.rb:240
    def config(**kwargs); end

    # pkg:gem/redis-client#lib/redis_client.rb:33
    def default_driver; end

    # pkg:gem/redis-client#lib/redis_client.rb:45
    def default_driver=(name); end

    # pkg:gem/redis-client#lib/redis_client.rb:22
    def driver(name); end

    # pkg:gem/redis-client#lib/redis_client.rb:254
    def new(arg = T.unsafe(nil), **kwargs); end

    # pkg:gem/redis-client#lib/redis_client.rb:49
    def now; end

    # pkg:gem/redis-client#lib/redis_client.rb:53
    def now_ms; end

    # pkg:gem/redis-client#lib/redis_client.rb:262
    def register(middleware); end

    # pkg:gem/redis-client#lib/redis_client.rb:18
    def register_driver(name, &block); end

    # pkg:gem/redis-client#lib/redis_client.rb:248
    def ring(*clients, **options); end

    # pkg:gem/redis-client#lib/redis_client.rb:244
    def sentinel(**kwargs); end
  end
end

# pkg:gem/redis-client#lib/redis_client.rb:215
class RedisClient::AuthenticationError < ::RedisClient::CommandError; end

# pkg:gem/redis-client#lib/redis_client/middlewares.rb:4
class RedisClient::BasicMiddleware
  # pkg:gem/redis-client#lib/redis_client/middlewares.rb:7
  def initialize(client); end

  # pkg:gem/redis-client#lib/redis_client/middlewares.rb:15
  def call(command, _config); end

  # pkg:gem/redis-client#lib/redis_client/middlewares.rb:18
  def call_pipelined(command, _config); end

  # pkg:gem/redis-client#lib/redis_client/middlewares.rb:5
  def client; end

  # pkg:gem/redis-client#lib/redis_client/middlewares.rb:11
  def connect(_config); end
end

# pkg:gem/redis-client#lib/redis_client.rb:168
class RedisClient::CannotConnectError < ::RedisClient::ConnectionError; end

# pkg:gem/redis-client#lib/redis_client.rb:175
class RedisClient::CheckoutTimeoutError < ::RedisClient::TimeoutError; end

# pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:4
class RedisClient::CircuitBreaker
  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:23
  def initialize(error_threshold:, error_timeout:, error_threshold_timeout: T.unsafe(nil), success_threshold: T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:21
  def error_threshold; end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:21
  def error_threshold_timeout; end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:21
  def error_timeout; end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:34
  def protect; end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:21
  def success_threshold; end

  private

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:80
  def record_error; end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:95
  def record_success; end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:65
  def refresh_state; end
end

# pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:5
module RedisClient::CircuitBreaker::Middleware
  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:10
  def call(_command, config); end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:14
  def call_pipelined(_commands, config); end

  # pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:6
  def connect(config); end
end

# pkg:gem/redis-client#lib/redis_client/circuit_breaker.rb:19
class RedisClient::CircuitBreaker::OpenCircuitError < ::RedisClient::CannotConnectError; end

# pkg:gem/redis-client#lib/redis_client/command_builder.rb:4
module RedisClient::CommandBuilder
  extend ::RedisClient::CommandBuilder

  # pkg:gem/redis-client#lib/redis_client/command_builder.rb:8
  def generate(args, kwargs = T.unsafe(nil)); end
end

# pkg:gem/redis-client#lib/redis_client.rb:194
class RedisClient::CommandError < ::RedisClient::Error
  include ::RedisClient::HasCommand
  include ::RedisClient::HasCode
  include ::RedisClient::Final

  class << self
    # pkg:gem/redis-client#lib/redis_client.rb:200
    def parse(error_message); end
  end
end

# pkg:gem/redis-client#lib/redis_client.rb:229
RedisClient::CommandError::ERRORS = T.let(T.unsafe(nil), Hash)

# pkg:gem/redis-client#lib/redis_client.rb:63
module RedisClient::Common
  # pkg:gem/redis-client#lib/redis_client.rb:67
  def initialize(config, id: T.unsafe(nil), connect_timeout: T.unsafe(nil), read_timeout: T.unsafe(nil), write_timeout: T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client.rb:64
  def config; end

  # pkg:gem/redis-client#lib/redis_client.rb:65
  def connect_timeout; end

  # pkg:gem/redis-client#lib/redis_client.rb:65
  def connect_timeout=(_arg0); end

  # pkg:gem/redis-client#lib/redis_client.rb:64
  def id; end

  # pkg:gem/redis-client#lib/redis_client.rb:88
  def node_for(_key); end

  # pkg:gem/redis-client#lib/redis_client.rb:64
  def nodes; end

  # pkg:gem/redis-client#lib/redis_client.rb:92
  def nodes_for(*keys); end

  # pkg:gem/redis-client#lib/redis_client.rb:65
  def read_timeout; end

  # pkg:gem/redis-client#lib/redis_client.rb:65
  def read_timeout=(_arg0); end

  # pkg:gem/redis-client#lib/redis_client.rb:84
  def timeout=(timeout); end

  # pkg:gem/redis-client#lib/redis_client.rb:65
  def write_timeout; end

  # pkg:gem/redis-client#lib/redis_client.rb:65
  def write_timeout=(_arg0); end
end

# pkg:gem/redis-client#lib/redis_client/config.rb:7
class RedisClient::Config
  include ::RedisClient::Config::Common

  # pkg:gem/redis-client#lib/redis_client/config.rb:223
  def initialize(url: T.unsafe(nil), host: T.unsafe(nil), port: T.unsafe(nil), path: T.unsafe(nil), username: T.unsafe(nil), password: T.unsafe(nil), db: T.unsafe(nil), **kwargs); end

  # pkg:gem/redis-client#lib/redis_client/config.rb:221
  def host; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:221
  def path; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:221
  def port; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:221
  def server_key; end
end

# pkg:gem/redis-client#lib/redis_client/config.rb:15
module RedisClient::Config::Common
  # pkg:gem/redis-client#lib/redis_client/config.rb:22
  def initialize(username: T.unsafe(nil), password: T.unsafe(nil), db: T.unsafe(nil), id: T.unsafe(nil), timeout: T.unsafe(nil), read_timeout: T.unsafe(nil), write_timeout: T.unsafe(nil), connect_timeout: T.unsafe(nil), idle_timeout: T.unsafe(nil), ssl: T.unsafe(nil), custom: T.unsafe(nil), ssl_params: T.unsafe(nil), driver: T.unsafe(nil), protocol: T.unsafe(nil), client_implementation: T.unsafe(nil), command_builder: T.unsafe(nil), inherit_socket: T.unsafe(nil), reconnect_attempts: T.unsafe(nil), middlewares: T.unsafe(nil), circuit_breaker: T.unsafe(nil), driver_info: T.unsafe(nil)); end

  # Build the library name for CLIENT SETINFO LIB-NAME.
  #
  # @param driver_info [String, Array<String>, nil] Upstream driver info
  # @return [String] Library name with optional upstream driver info
  # @raise [ArgumentError] if driver_info is not a String or Array
  #
  # pkg:gem/redis-client#lib/redis_client/config.rb:144
  def build_lib_name; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def circuit_breaker; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def command_builder; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def connect_timeout; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:95
  def connection_prelude; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def custom; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def db; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def driver; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def driver_info; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def id; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def idle_timeout; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def inherit_socket; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def middlewares_stack; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:171
  def new_client(**kwargs); end

  # pkg:gem/redis-client#lib/redis_client/config.rb:166
  def new_pool(**kwargs); end

  # pkg:gem/redis-client#lib/redis_client/config.rb:131
  def password; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def protocol; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def read_timeout; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:158
  def resolved?; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:175
  def retriable?(attempt); end

  # pkg:gem/redis-client#lib/redis_client/config.rb:179
  def retry_connecting?(attempt, _error); end

  # pkg:gem/redis-client#lib/redis_client/config.rb:162
  def sentinel?; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:197
  def server_url; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def ssl; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:20
  def ssl?; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:191
  def ssl_context; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def ssl_params; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:135
  def username; end

  # pkg:gem/redis-client#lib/redis_client/config.rb:16
  def write_timeout; end
end

# pkg:gem/redis-client#lib/redis_client/config.rb:12
RedisClient::Config::DEFAULT_DB = T.let(T.unsafe(nil), Integer)

# pkg:gem/redis-client#lib/redis_client/config.rb:9
RedisClient::Config::DEFAULT_HOST = T.let(T.unsafe(nil), String)

# pkg:gem/redis-client#lib/redis_client/config.rb:13
RedisClient::Config::DEFAULT_IDLE_TIMEOUT = T.let(T.unsafe(nil), Float)

# pkg:gem/redis-client#lib/redis_client/config.rb:10
RedisClient::Config::DEFAULT_PORT = T.let(T.unsafe(nil), Integer)

# pkg:gem/redis-client#lib/redis_client/config.rb:8
RedisClient::Config::DEFAULT_TIMEOUT = T.let(T.unsafe(nil), Float)

# pkg:gem/redis-client#lib/redis_client/config.rb:11
RedisClient::Config::DEFAULT_USERNAME = T.let(T.unsafe(nil), String)

# pkg:gem/redis-client#lib/redis_client.rb:167
class RedisClient::ConnectionError < ::RedisClient::Error; end

# pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:4
module RedisClient::ConnectionMixin
  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:8
  def initialize(config); end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:34
  def call(command, timeout); end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:49
  def call_pipelined(commands, timeouts, exception: T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:20
  def close; end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:6
  def config; end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:102
  def connection_error(message); end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:87
  def connection_timeout(timeout); end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:96
  def protocol_error(message); end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:15
  def reconnect; end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:5
  def retry_attempt; end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:5
  def retry_attempt=(_arg0); end

  # pkg:gem/redis-client#lib/redis_client/connection_mixin.rb:25
  def revalidate; end
end

# pkg:gem/redis-client#lib/redis_client.rb:147
class RedisClient::Error < ::StandardError
  include ::RedisClient::HasConfig
  include ::RedisClient::Retriable

  # pkg:gem/redis-client#lib/redis_client.rb:159
  def _set_next_error(error); end

  # pkg:gem/redis-client#lib/redis_client.rb:151
  def next_error; end

  class << self
    # pkg:gem/redis-client#lib/redis_client.rb:153
    def with_config(message, config = T.unsafe(nil)); end
  end
end

# pkg:gem/redis-client#lib/redis_client.rb:170
class RedisClient::FailoverError < ::RedisClient::ConnectionError; end

# pkg:gem/redis-client#lib/redis_client.rb:130
module RedisClient::Final
  # pkg:gem/redis-client#lib/redis_client.rb:131
  def _set_retry_attempt(_retry_attempt); end

  # pkg:gem/redis-client#lib/redis_client.rb:142
  def final?; end

  # pkg:gem/redis-client#lib/redis_client.rb:138
  def retriable?; end

  # pkg:gem/redis-client#lib/redis_client.rb:134
  def retry_attempt; end
end

# pkg:gem/redis-client#lib/redis_client.rb:185
module RedisClient::HasCode
  # pkg:gem/redis-client#lib/redis_client.rb:188
  def initialize(message = T.unsafe(nil), code = T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client.rb:186
  def code; end
end

# pkg:gem/redis-client#lib/redis_client.rb:177
module RedisClient::HasCommand
  # pkg:gem/redis-client#lib/redis_client.rb:180
  def _set_command(command); end

  # pkg:gem/redis-client#lib/redis_client.rb:178
  def command; end
end

# pkg:gem/redis-client#lib/redis_client.rb:98
module RedisClient::HasConfig
  # pkg:gem/redis-client#lib/redis_client.rb:101
  def _set_config(config); end

  # pkg:gem/redis-client#lib/redis_client.rb:99
  def config; end

  # pkg:gem/redis-client#lib/redis_client.rb:105
  def message; end
end

# pkg:gem/redis-client#lib/redis_client.rb:225
class RedisClient::MasterDownError < ::RedisClient::ConnectionError
  include ::RedisClient::HasCommand
  include ::RedisClient::HasCode
end

# pkg:gem/redis-client#lib/redis_client/middlewares.rb:21
class RedisClient::Middlewares < ::RedisClient::BasicMiddleware; end

# pkg:gem/redis-client#lib/redis_client.rb:609
class RedisClient::Multi
  # pkg:gem/redis-client#lib/redis_client.rb:610
  def initialize(command_builder); end

  # pkg:gem/redis-client#lib/redis_client.rb:652
  def _blocks; end

  # pkg:gem/redis-client#lib/redis_client.rb:672
  def _coerce!(results); end

  # pkg:gem/redis-client#lib/redis_client.rb:648
  def _commands; end

  # pkg:gem/redis-client#lib/redis_client.rb:660
  def _empty?; end

  # pkg:gem/redis-client#lib/redis_client.rb:668
  def _retryable?; end

  # pkg:gem/redis-client#lib/redis_client.rb:656
  def _size; end

  # pkg:gem/redis-client#lib/redis_client.rb:664
  def _timeouts; end

  # pkg:gem/redis-client#lib/redis_client.rb:618
  def call(*command, **kwargs, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:632
  def call_once(*command, **kwargs, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:640
  def call_once_v(command, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:625
  def call_v(command, &block); end
end

# pkg:gem/redis-client#lib/redis_client.rb:219
class RedisClient::NoScriptError < ::RedisClient::CommandError; end

# pkg:gem/redis-client#lib/redis_client.rb:218
class RedisClient::OutOfMemoryError < ::RedisClient::CommandError; end

# pkg:gem/redis-client#lib/redis_client/pid_cache.rb:4
module RedisClient::PIDCache
  class << self
    # pkg:gem/redis-client#lib/redis_client/pid_cache.rb:10
    def pid; end

    # pkg:gem/redis-client#lib/redis_client/pid_cache.rb:12
    def update!; end
  end
end

# pkg:gem/redis-client#lib/redis_client/pid_cache.rb:18
module RedisClient::PIDCache::CoreExt
  # pkg:gem/redis-client#lib/redis_client/pid_cache.rb:19
  def _fork; end
end

# pkg:gem/redis-client#lib/redis_client.rb:216
class RedisClient::PermissionError < ::RedisClient::CommandError; end

# pkg:gem/redis-client#lib/redis_client.rb:688
class RedisClient::Pipeline < ::RedisClient::Multi
  # pkg:gem/redis-client#lib/redis_client.rb:689
  def initialize(_command_builder); end

  # pkg:gem/redis-client#lib/redis_client.rb:720
  def _coerce!(results); end

  # pkg:gem/redis-client#lib/redis_client.rb:716
  def _empty?; end

  # pkg:gem/redis-client#lib/redis_client.rb:712
  def _timeouts; end

  # pkg:gem/redis-client#lib/redis_client.rb:694
  def blocking_call(timeout, *command, **kwargs, &block); end

  # pkg:gem/redis-client#lib/redis_client.rb:703
  def blocking_call_v(timeout, command, &block); end
end

# pkg:gem/redis-client#lib/redis_client/pooled.rb:6
class RedisClient::Pooled
  include ::RedisClient::Common

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:11
  def initialize(config, id: T.unsafe(nil), connect_timeout: T.unsafe(nil), read_timeout: T.unsafe(nil), write_timeout: T.unsafe(nil), **kwargs); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def blocking_call(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def blocking_call_v(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def call(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def call_once(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def call_once_v(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def call_v(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:37
  def close; end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:64
  def hscan(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def multi(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def pipelined(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:55
  def pubsub(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:64
  def scan(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:48
  def size; end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:64
  def sscan(*args, **, &block); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:35
  def then(options = T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:25
  def with(options = T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:64
  def zscan(*args, **, &block); end

  private

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:82
  def new_pool; end

  # pkg:gem/redis-client#lib/redis_client/pooled.rb:78
  def pool; end
end

# pkg:gem/redis-client#lib/redis_client/pooled.rb:7
RedisClient::Pooled::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# pkg:gem/redis-client#lib/redis_client.rb:164
class RedisClient::ProtocolError < ::RedisClient::Error; end

# pkg:gem/redis-client#lib/redis_client.rb:572
class RedisClient::PubSub
  # pkg:gem/redis-client#lib/redis_client.rb:573
  def initialize(raw_connection, command_builder); end

  # pkg:gem/redis-client#lib/redis_client.rb:578
  def call(*command, **kwargs); end

  # pkg:gem/redis-client#lib/redis_client.rb:583
  def call_v(command); end

  # pkg:gem/redis-client#lib/redis_client.rb:588
  def close; end

  # pkg:gem/redis-client#lib/redis_client.rb:594
  def next_event(timeout = T.unsafe(nil)); end

  private

  # pkg:gem/redis-client#lib/redis_client.rb:606
  def raw_connection; end
end

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:4
module RedisClient::RESP3
  private

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:36
  def dump(command, buffer = T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:57
  def dump_any(object, buffer); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:68
  def dump_array(array, buffer); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:84
  def dump_hash(hash, buffer); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:93
  def dump_numeric(numeric, buffer); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:76
  def dump_set(set, buffer); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:97
  def dump_string(string, buffer); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:103
  def dump_symbol(symbol, buffer); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:49
  def load(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:53
  def new_buffer; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:112
  def parse(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:166
  def parse_array(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:218
  def parse_blob(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:155
  def parse_boolean(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:200
  def parse_double(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:151
  def parse_error(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:196
  def parse_integer(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:174
  def parse_map(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:213
  def parse_null(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:182
  def parse_push(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:186
  def parse_sequence(io, size); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:170
  def parse_set(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:145
  def parse_string(io); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:227
  def parse_verbatim_string(io); end

  class << self
    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:36
    def dump(command, buffer = T.unsafe(nil)); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:57
    def dump_any(object, buffer); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:68
    def dump_array(array, buffer); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:84
    def dump_hash(hash, buffer); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:93
    def dump_numeric(numeric, buffer); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:76
    def dump_set(set, buffer); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:97
    def dump_string(string, buffer); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:103
    def dump_symbol(symbol, buffer); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:49
    def load(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:53
    def new_buffer; end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:112
    def parse(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:166
    def parse_array(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:218
    def parse_blob(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:155
    def parse_boolean(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:200
    def parse_double(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:151
    def parse_error(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:196
    def parse_integer(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:174
    def parse_map(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:213
    def parse_null(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:182
    def parse_push(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:186
    def parse_sequence(io, size); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:170
    def parse_set(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:145
    def parse_string(io); end

    # pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:227
    def parse_verbatim_string(io); end
  end
end

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:13
RedisClient::RESP3::DUMP_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:11
RedisClient::RESP3::EOL = T.let(T.unsafe(nil), String)

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:12
RedisClient::RESP3::EOL_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:7
class RedisClient::RESP3::Error < ::RedisClient::Error; end

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:34
RedisClient::RESP3::INTEGER_RANGE = T.let(T.unsafe(nil), Range)

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:19
RedisClient::RESP3::PARSER_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:9
class RedisClient::RESP3::SyntaxError < ::RedisClient::RESP3::Error; end

# pkg:gem/redis-client#lib/redis_client/ruby_connection/resp3.rb:8
class RedisClient::RESP3::UnknownType < ::RedisClient::RESP3::Error; end

# pkg:gem/redis-client#lib/redis_client.rb:221
class RedisClient::ReadOnlyError < ::RedisClient::ConnectionError
  include ::RedisClient::HasCommand
  include ::RedisClient::HasCode
end

# pkg:gem/redis-client#lib/redis_client.rb:173
class RedisClient::ReadTimeoutError < ::RedisClient::TimeoutError; end

# pkg:gem/redis-client#lib/redis_client.rb:112
module RedisClient::Retriable
  # pkg:gem/redis-client#lib/redis_client.rb:113
  def _set_retry_attempt(retry_attempt); end

  # pkg:gem/redis-client#lib/redis_client.rb:125
  def final?; end

  # pkg:gem/redis-client#lib/redis_client.rb:121
  def retriable?; end

  # pkg:gem/redis-client#lib/redis_client.rb:117
  def retry_attempt; end
end

# pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:6
class RedisClient::RubyConnection
  include ::RedisClient::ConnectionMixin

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:43
  def initialize(config, connect_timeout:, read_timeout:, write_timeout:); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:55
  def close; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:51
  def connected?; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:107
  def measure_round_trip_delay; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:95
  def read(timeout = T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:60
  def read_timeout=(timeout); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:70
  def write(command); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:83
  def write_multi(commands); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:65
  def write_timeout=(timeout); end

  private

  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:115
  def connect; end

  # Linux
  # macOS
  # unknown POSIX
  # unknown
  #
  # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:179
  def enable_socket_keep_alive(socket); end

  class << self
    # pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:14
    def ssl_context(ssl_params); end
  end
end

# pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:7
class RedisClient::RubyConnection::BufferedIO
  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:16
  def initialize(io, read_timeout:, write_timeout:, chunk_size: T.unsafe(nil)); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:89
  def close; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:93
  def closed?; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:97
  def eof?; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:150
  def getbyte; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:26
  def gets_chomp; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:159
  def gets_integer; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:37
  def read_chomp(bytes); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:11
  def read_timeout; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:11
  def read_timeout=(_arg0); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:121
  def skip(offset); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:101
  def with_timeout(new_timeout); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:127
  def write(string); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:11
  def write_timeout; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:11
  def write_timeout=(_arg0); end

  private

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:44
  def ensure_line; end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:184
  def ensure_remaining(bytes); end

  # pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:191
  def fill_buffer(strict, size = T.unsafe(nil)); end
end

# Ruby 3.2+
#
# pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:14
RedisClient::RubyConnection::BufferedIO::ENCODING = T.let(T.unsafe(nil), Encoding)

# pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:8
RedisClient::RubyConnection::BufferedIO::EOL = T.let(T.unsafe(nil), String)

# pkg:gem/redis-client#lib/redis_client/ruby_connection/buffered_io.rb:9
RedisClient::RubyConnection::BufferedIO::EOL_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:164
RedisClient::RubyConnection::KEEP_ALIVE_INTERVAL = T.let(T.unsafe(nil), Integer)

# Longer than hiredis defaults
#
# pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:166
RedisClient::RubyConnection::KEEP_ALIVE_PROBES = T.let(T.unsafe(nil), Integer)

# Same as hiredis defaults
#
# pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:165
RedisClient::RubyConnection::KEEP_ALIVE_TTL = T.let(T.unsafe(nil), Integer)

# pkg:gem/redis-client#lib/redis_client/ruby_connection.rb:41
RedisClient::RubyConnection::SUPPORTS_RESOLV_TIMEOUT = T.let(T.unsafe(nil), TrueClass)

# pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:4
class RedisClient::SentinelConfig
  include ::RedisClient::Config::Common

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:12
  def initialize(sentinels:, sentinel_password: T.unsafe(nil), sentinel_username: T.unsafe(nil), role: T.unsafe(nil), name: T.unsafe(nil), url: T.unsafe(nil), **client_config); end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:118
  def check_role!(role); end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:97
  def host; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:10
  def name; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:105
  def path; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:101
  def port; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:87
  def reset; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:136
  def resolved?; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:109
  def retry_connecting?(attempt, error); end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:114
  def sentinel?; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:81
  def sentinels; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:93
  def server_key; end

  private

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:155
  def config; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:202
  def each_sentinel; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:228
  def refresh_sentinels(sentinel_client); end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:165
  def resolve_master; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:184
  def resolve_replica; end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:180
  def sentinel_client(sentinel_config); end

  # pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:144
  def sentinels_to_configs(sentinels); end
end

# pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:8
RedisClient::SentinelConfig::DEFAULT_RECONNECT_ATTEMPTS = T.let(T.unsafe(nil), Integer)

# pkg:gem/redis-client#lib/redis_client/sentinel_config.rb:7
RedisClient::SentinelConfig::SENTINEL_DELAY = T.let(T.unsafe(nil), Float)

# pkg:gem/redis-client#lib/redis_client.rb:172
class RedisClient::TimeoutError < ::RedisClient::ConnectionError; end

# pkg:gem/redis-client#lib/redis_client/url_config.rb:6
class RedisClient::URLConfig
  # pkg:gem/redis-client#lib/redis_client/url_config.rb:9
  def initialize(url); end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:30
  def db; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:56
  def host; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:48
  def password; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:62
  def path; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:68
  def port; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:26
  def ssl?; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:7
  def uri; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:7
  def url; end

  # pkg:gem/redis-client#lib/redis_client/url_config.rb:44
  def username; end
end

# pkg:gem/redis-client#lib/redis_client.rb:165
class RedisClient::UnsupportedServer < ::RedisClient::Error; end

# pkg:gem/redis-client#lib/redis_client/version.rb:4
RedisClient::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/redis-client#lib/redis_client.rb:174
class RedisClient::WriteTimeoutError < ::RedisClient::TimeoutError; end

# pkg:gem/redis-client#lib/redis_client.rb:217
class RedisClient::WrongTypeError < ::RedisClient::CommandError; end
