# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/unicode-display_width/all/unicode-display_width.rbi
#
# unicode-display_width-1.5.0
module Unicode
end
module Unicode::DisplayWidth
  def self.emoji_extra_width_of(string, ambiguous = nil, overwrite = nil, _ = nil); end
  def self.of(string, ambiguous = nil, overwrite = nil, options = nil); end
end
