# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/ftrace/generic.proto

require 'google/protobuf'


descriptor_data = "\n*protos/perfetto/trace/ftrace/generic.proto\x12\x0fperfetto.protos\"\xc2\x01\n\x12GenericFtraceEvent\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x38\n\x05\x66ield\x18\x02 \x03(\x0b\x32).perfetto.protos.GenericFtraceEvent.Field\x1a^\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\tstr_value\x18\x03 \x01(\tH\x00\x12\x13\n\tint_value\x18\x04 \x01(\x03H\x00\x12\x14\n\nuint_value\x18\x05 \x01(\x04H\x00\x42\x07\n\x05value\"\xbe\x01\n\x0bKprobeEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\x04type\x18\x02 \x01(\x0e\x32\'.perfetto.protos.KprobeEvent.KprobeType\"j\n\nKprobeType\x12\x17\n\x13KPROBE_TYPE_UNKNOWN\x10\x00\x12\x15\n\x11KPROBE_TYPE_BEGIN\x10\x01\x12\x13\n\x0fKPROBE_TYPE_END\x10\x02\x12\x17\n\x13KPROBE_TYPE_INSTANT\x10\x03"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    GenericFtraceEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.GenericFtraceEvent").msgclass
    GenericFtraceEvent::Field = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.GenericFtraceEvent.Field").msgclass
    KprobeEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.KprobeEvent").msgclass
    KprobeEvent::KprobeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.KprobeEvent.KprobeType").enummodule
  end
end
