# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/chrome/frame_times.proto

require 'google/protobuf'

require 'protos/perfetto/metrics/custom_options_pb'


descriptor_data = "\n0protos/perfetto/metrics/chrome/frame_times.proto\x12\x0fperfetto.protos\x1a,protos/perfetto/metrics/custom_options.proto\"\xd8\x01\n\nFrameTimes\x12*\n\nframe_time\x18\x01 \x03(\x01\x42\x16\x8a\xb5\x18\x12ms_smallerIsBetter\x12.\n\x0e\x65xp_frame_time\x18\x02 \x03(\x01\x42\x16\x8a\xb5\x18\x12ms_smallerIsBetter\x12\x34\n\x0f\x61vg_surface_fps\x18\x03 \x01(\x01\x42\x1b\x8a\xb5\x18\x17unitless_biggerIsBetter\x12\x38\n\x13\x65xp_avg_surface_fps\x18\x04 \x01(\x01\x42\x1b\x8a\xb5\x18\x17unitless_biggerIsBetter"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    FrameTimes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.FrameTimes").msgclass
  end
end
