# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/chrome/scroll_jank_v3.proto

require 'google/protobuf'

require 'protos/perfetto/metrics/custom_options_pb'


descriptor_data = "\n3protos/perfetto/metrics/chrome/scroll_jank_v3.proto\x12\x0fperfetto.protos\x1a,protos/perfetto/metrics/custom_options.proto\"\xe3\x05\n\x12\x43hromeScrollJankV3\x12\x32\n\x10trace_num_frames\x18\x01 \x01(\x03\x42\x18\x8a\xb5\x18\x14\x63ount_biggerIsBetter\x12\x39\n\x16trace_num_janky_frames\x18\x02 \x01(\x03\x42\x19\x8a\xb5\x18\x15\x63ount_smallerIsBetter\x12<\n\x1ctrace_scroll_jank_percentage\x18\x03 \x01(\x01\x42\x16\x8a\xb5\x18\x12n%_smallerIsBetter\x12\x30\n\x11vsync_interval_ms\x18\x04 \x01(\x01\x42\x15\x8a\xb5\x18\x11ms_biggerIsBetter\x12;\n\x07scrolls\x18\x05 \x03(\x0b\x32*.perfetto.protos.ChromeScrollJankV3.Scroll\x1a\xb0\x03\n\x06Scroll\x12,\n\nnum_frames\x18\x01 \x01(\x03\x42\x18\x8a\xb5\x18\x14\x63ount_biggerIsBetter\x12\x33\n\x10num_janky_frames\x18\x02 \x01(\x03\x42\x19\x8a\xb5\x18\x15\x63ount_smallerIsBetter\x12\x36\n\x16scroll_jank_percentage\x18\x03 \x01(\x01\x42\x16\x8a\xb5\x18\x12n%_smallerIsBetter\x12@\n\x1amax_delay_since_last_frame\x18\x04 \x01(\x01\x42\x1c\x8a\xb5\x18\x18unitless_smallerIsBetter\x12V\n\x12scroll_jank_causes\x18\x05 \x03(\x0b\x32:.perfetto.protos.ChromeScrollJankV3.Scroll.ScrollJankCause\x1aq\n\x0fScrollJankCause\x12\r\n\x05\x63\x61use\x18\x01 \x01(\t\x12\x11\n\tsub_cause\x18\x02 \x01(\t\x12<\n\x16\x64\x65lay_since_last_frame\x18\x03 \x01(\x01\x42\x1c\x8a\xb5\x18\x18unitless_smallerIsBetter"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    ChromeScrollJankV3 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.ChromeScrollJankV3").msgclass
    ChromeScrollJankV3::Scroll = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.ChromeScrollJankV3.Scroll").msgclass
    ChromeScrollJankV3::Scroll::ScrollJankCause = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.ChromeScrollJankV3.Scroll.ScrollJankCause").msgclass
  end
end
