version: "2"
exclude_patterns:
  - "spec/"
  - "lib/graphql/language/lexer.rb"
  - "lib/graphql/language/parser.rb"
  # plugin - duplication - is failing on these
  - "spec/graphql/language/printer_spec.rb"
  - "lib/graphql/compatibility/query_parser_specification.rb"
