AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'lib/graphql/language/lexer.rb'
    - 'lib/graphql/language/parser.rb'
    - 'gemfiles/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# def ...
# end
Lint/DefEndAlignment:
  EnforcedStyleAlignWith: def

# value = if
#   # ...
# end
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/UselessAssignment:
  Enabled: true

Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/IndentationWidth:
  Width: 2

Style/LambdaCall:
  EnforcedStyle: call

Layout/LeadingCommentSpace:
  Enabled: true

Naming/MethodName:
  EnforcedStyle: snake_case

Style/WordArray:
  EnforcedStyle: brackets

# ->(...) { ... }
Layout/SpaceInLambdaLiteral:
  Enabled: true # Default is "require_no_space"
