gem:
  # Add your `gem` command parameters here:
  #
  exclude:
  - graphql
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
