# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/track_event/screenshot.proto

require 'google/protobuf'


descriptor_data = "\n2protos/perfetto/trace/track_event/screenshot.proto\x12\x0fperfetto.protos\"\x1f\n\nScreenshot\x12\x11\n\tjpg_image\x18\x01 \x01(\x0c"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    Screenshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.Screenshot").msgclass
  end
end
