# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/track_event/source_location.proto

require 'google/protobuf'


descriptor_data = "\n7protos/perfetto/trace/track_event/source_location.proto\x12\x0fperfetto.protos\"M\n\x1aUnsymbolizedSourceLocation\x12\x0b\n\x03iid\x18\x01 \x01(\x04\x12\x12\n\nmapping_id\x18\x02 \x01(\x04\x12\x0e\n\x06rel_pc\x18\x03 \x01(\x04\"\\\n\x0eSourceLocation\x12\x0b\n\x03iid\x18\x01 \x01(\x04\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x15\n\rfunction_name\x18\x03 \x01(\t\x12\x13\n\x0bline_number\x18\x04 \x01(\r"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    UnsymbolizedSourceLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.UnsymbolizedSourceLocation").msgclass
    SourceLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.SourceLocation").msgclass
  end
end
