# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/android/android_anomaly_metric.proto

require 'google/protobuf'


descriptor_data = "\n<protos/perfetto/metrics/android/android_anomaly_metric.proto\x12\x0fperfetto.protos\"\xdb\x03\n\x14\x41ndroidAnomalyMetric\x12<\n\x06\x62inder\x18\x01 \x01(\x0b\x32,.perfetto.protos.AndroidAnomalyMetric.Binder\x1a|\n\x0eProcessAnomaly\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x38\n\x04unit\x18\x03 \x01(\x0e\x32*.perfetto.protos.AndroidAnomalyMetric.Unit\x12\r\n\x05value\x18\x04 \x01(\r\x1a\xd2\x01\n\x06\x42inder\x12\x63\n%max_incoming_process_count_per_second\x18\x01 \x03(\x0b\x32\x34.perfetto.protos.AndroidAnomalyMetric.ProcessAnomaly\x12\x63\n%max_outgoing_process_count_per_second\x18\x02 \x03(\x0b\x32\x34.perfetto.protos.AndroidAnomalyMetric.ProcessAnomaly\"2\n\x04Unit\x12\x14\n\x10UNIT_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43OUNT_PER_SECOND\x10\x01"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidAnomalyMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidAnomalyMetric").msgclass
    AndroidAnomalyMetric::ProcessAnomaly = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidAnomalyMetric.ProcessAnomaly").msgclass
    AndroidAnomalyMetric::Binder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidAnomalyMetric.Binder").msgclass
    AndroidAnomalyMetric::Unit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidAnomalyMetric.Unit").enummodule
  end
end
