# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/android/android_garbage_collection_stats.proto

require 'google/protobuf'


descriptor_data = "\nFprotos/perfetto/metrics/android/android_garbage_collection_stats.proto\x12\x0fperfetto.protos\"\xd7\x03\n\x1d\x41ndroidGarbageCollectionStats\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x0b\n\x03\x64ur\x18\x02 \x01(\x03\x12\x15\n\rheap_size_mbs\x18\x03 \x01(\x01\x12\x14\n\x0cheap_size_mb\x18\x04 \x01(\x01\x12\x19\n\x11heap_allocated_mb\x18\x05 \x01(\x01\x12\x1c\n\x14heap_allocation_rate\x18\x06 \x01(\x01\x12\x15\n\rheap_live_mbs\x18\x07 \x01(\x01\x12\x16\n\x0eheap_total_mbs\x18\x08 \x01(\x01\x12\x18\n\x10heap_utilization\x18\t \x01(\x01\x12\x16\n\x0egc_running_dur\x18\n \x01(\x03\x12\x17\n\x0fgc_running_rate\x18\x0b \x01(\x01\x12\x1d\n\x15gc_running_efficiency\x18\x0c \x01(\x01\x12%\n\x1dgc_during_android_startup_dur\x18\r \x01(\x03\x12!\n\x19total_android_startup_dur\x18\x0e \x01(\x03\x12&\n\x1egc_during_android_startup_rate\x18\x0f \x01(\x01\x12,\n$gc_during_android_startup_efficiency\x18\x10 \x01(\x01"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidGarbageCollectionStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidGarbageCollectionStats").msgclass
  end
end
