# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/android/cpu_metric.proto

require 'google/protobuf'

require 'protos/perfetto/metrics/android/process_metadata_pb'


descriptor_data = "\n0protos/perfetto/metrics/android/cpu_metric.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\x9f\x07\n\x10\x41ndroidCpuMetric\x12?\n\x0cprocess_info\x18\x01 \x03(\x0b\x32).perfetto.protos.AndroidCpuMetric.Process\x1ap\n\x07Metrics\x12\x0f\n\x07mcycles\x18\x01 \x01(\x03\x12\x12\n\nruntime_ns\x18\x02 \x01(\x03\x12\x14\n\x0cmin_freq_khz\x18\x03 \x01(\x03\x12\x14\n\x0cmax_freq_khz\x18\x04 \x01(\x03\x12\x14\n\x0c\x61vg_freq_khz\x18\x05 \x01(\x03\x1aX\n\x08\x43oreData\x12\n\n\x02id\x18\x01 \x01(\r\x12:\n\x07metrics\x18\x06 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.MetricsJ\x04\x08\x02\x10\x06\x1aX\n\x0c\x43oreTypeData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12:\n\x07metrics\x18\x02 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.Metrics\x1a\xd5\x01\n\x06Thread\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x07metrics\x18\x04 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.Metrics\x12\x38\n\x04\x63ore\x18\x02 \x03(\x0b\x32*.perfetto.protos.AndroidCpuMetric.CoreData\x12\x41\n\tcore_type\x18\x05 \x03(\x0b\x32..perfetto.protos.AndroidCpuMetric.CoreTypeDataJ\x04\x08\x03\x10\x04\x1a\xcb\x02\n\x07Process\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x38\n\x07process\x18\x08 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12:\n\x07metrics\x18\x04 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.Metrics\x12\x39\n\x07threads\x18\x06 \x03(\x0b\x32(.perfetto.protos.AndroidCpuMetric.Thread\x12\x38\n\x04\x63ore\x18\x07 \x03(\x0b\x32*.perfetto.protos.AndroidCpuMetric.CoreData\x12\x41\n\tcore_type\x18\x05 \x03(\x0b\x32..perfetto.protos.AndroidCpuMetric.CoreTypeDataJ\x04\x08\x03\x10\x04"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidCpuMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidCpuMetric").msgclass
    AndroidCpuMetric::Metrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidCpuMetric.Metrics").msgclass
    AndroidCpuMetric::CoreData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidCpuMetric.CoreData").msgclass
    AndroidCpuMetric::CoreTypeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidCpuMetric.CoreTypeData").msgclass
    AndroidCpuMetric::Thread = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidCpuMetric.Thread").msgclass
    AndroidCpuMetric::Process = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidCpuMetric.Process").msgclass
  end
end
