# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/android/g2d_metric.proto

require 'google/protobuf'


descriptor_data = "\n0protos/perfetto/metrics/android/g2d_metric.proto\x12\x0fperfetto.protos\"\xba\x03\n\nG2dMetrics\x12\x35\n\x06g2d_hw\x18\x01 \x01(\x0b\x32%.perfetto.protos.G2dMetrics.G2dMetric\x12\x35\n\x06g2d_sw\x18\x02 \x01(\x0b\x32%.perfetto.protos.G2dMetrics.G2dMetric\x1a\x87\x01\n\x0bG2dInstance\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x66rame_count\x18\x05 \x01(\r\x12\x13\n\x0b\x65rror_count\x18\x06 \x01(\r\x12\x12\n\nmax_dur_ms\x18\x07 \x01(\x01\x12\x12\n\nmin_dur_ms\x18\x08 \x01(\x01\x12\x12\n\navg_dur_ms\x18\t \x01(\x01J\x04\x08\x02\x10\x05\x1a\xb3\x01\n\tG2dMetric\x12:\n\tinstances\x18\x01 \x03(\x0b\x32\'.perfetto.protos.G2dMetrics.G2dInstance\x12\x13\n\x0b\x66rame_count\x18\x05 \x01(\r\x12\x13\n\x0b\x65rror_count\x18\x06 \x01(\r\x12\x12\n\nmax_dur_ms\x18\x07 \x01(\x01\x12\x12\n\nmin_dur_ms\x18\x08 \x01(\x01\x12\x12\n\navg_dur_ms\x18\t \x01(\x01J\x04\x08\x02\x10\x05"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    G2dMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.G2dMetrics").msgclass
    G2dMetrics::G2dInstance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.G2dMetrics.G2dInstance").msgclass
    G2dMetrics::G2dMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.G2dMetrics.G2dMetric").msgclass
  end
end
