# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/android/rt_runtime_metric.proto

require 'google/protobuf'


descriptor_data = "\n7protos/perfetto/metrics/android/rt_runtime_metric.proto\x12\x0fperfetto.protos\"\xc4\x01\n\x16\x41ndroidRtRuntimeMetric\x12\x13\n\x0bmax_runtime\x18\x01 \x01(\x03\x12\x16\n\x0eover_5ms_count\x18\x02 \x01(\x03\x12J\n\x11longest_rt_slices\x18\x03 \x03(\x0b\x32/.perfetto.protos.AndroidRtRuntimeMetric.RtSlice\x1a\x31\n\x07RtSlice\x12\r\n\x05tname\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\x03\x12\x0b\n\x03\x64ur\x18\x03 \x01(\x03"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidRtRuntimeMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidRtRuntimeMetric").msgclass
    AndroidRtRuntimeMetric::RtSlice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidRtRuntimeMetric.RtSlice").msgclass
  end
end
