# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/android/simpleperf.proto

require 'google/protobuf'


descriptor_data = "\n0protos/perfetto/metrics/android/simpleperf.proto\x12\x0fperfetto.protos\"\xc8\x03\n\x17\x41ndroidSimpleperfMetric\x12\x14\n\x0curgent_ratio\x18\x01 \x01(\x01\x12H\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x38.perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric\x1a\xcc\x02\n\x0fPerfEventMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12S\n\tprocesses\x18\x02 \x03(\x0b\x32@.perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric.Process\x12\r\n\x05total\x18\x03 \x01(\x01\x1a?\n\x06Thread\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x63pu\x18\x03 \x01(\x05\x12\r\n\x05total\x18\x04 \x01(\x01\x1a\x85\x01\n\x07Process\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12P\n\x07threads\x18\x03 \x03(\x0b\x32?.perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric.Thread\x12\r\n\x05total\x18\x04 \x01(\x01"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidSimpleperfMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidSimpleperfMetric").msgclass
    AndroidSimpleperfMetric::PerfEventMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric").msgclass
    AndroidSimpleperfMetric::PerfEventMetric::Thread = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric.Thread").msgclass
    AndroidSimpleperfMetric::PerfEventMetric::Process = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric.Process").msgclass
  end
end
