# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/metrics/android/surfaceflinger.proto

require 'google/protobuf'


descriptor_data = "\n4protos/perfetto/metrics/android/surfaceflinger.proto\x12\x0fperfetto.protos\"\xd5\x04\n\x1b\x41ndroidSurfaceflingerMetric\x12\x15\n\rmissed_frames\x18\x01 \x01(\r\x12\x19\n\x11missed_hwc_frames\x18\x02 \x01(\r\x12\x19\n\x11missed_gpu_frames\x18\x03 \x01(\r\x12\x19\n\x11missed_frame_rate\x18\x04 \x01(\x01\x12\x1d\n\x15missed_hwc_frame_rate\x18\x05 \x01(\x01\x12\x1d\n\x15missed_gpu_frame_rate\x18\x06 \x01(\x01\x12\x17\n\x0fgpu_invocations\x18\x07 \x01(\r\x12\x1e\n\x16\x61vg_gpu_waiting_dur_ms\x18\x08 \x01(\x01\x12*\n\"total_non_empty_gpu_waiting_dur_ms\x18\t \x01(\x01\x12[\n\x13metrics_per_display\x18\n \x03(\x0b\x32>.perfetto.protos.AndroidSurfaceflingerMetric.MetricsPerDisplay\x1a\xcd\x01\n\x11MetricsPerDisplay\x12\x12\n\ndisplay_id\x18\x01 \x01(\t\x12\x15\n\rmissed_frames\x18\x02 \x01(\r\x12\x19\n\x11missed_hwc_frames\x18\x03 \x01(\r\x12\x19\n\x11missed_gpu_frames\x18\x04 \x01(\r\x12\x19\n\x11missed_frame_rate\x18\x05 \x01(\x01\x12\x1d\n\x15missed_hwc_frame_rate\x18\x06 \x01(\x01\x12\x1d\n\x15missed_gpu_frame_rate\x18\x07 \x01(\x01"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidSurfaceflingerMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidSurfaceflingerMetric").msgclass
    AndroidSurfaceflingerMetric::MetricsPerDisplay = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidSurfaceflingerMetric.MetricsPerDisplay").msgclass
  end
end
