# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/config/android/android_polled_state_config.proto

require 'google/protobuf'


descriptor_data = "\n@protos/perfetto/config/android/android_polled_state_config.proto\x12\x0fperfetto.protos\"+\n\x18\x41ndroidPolledStateConfig\x12\x0f\n\x07poll_ms\x18\x01 \x01(\r"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidPolledStateConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidPolledStateConfig").msgclass
  end
end
