# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/power/android_entity_state_residency.proto

require 'google/protobuf'


descriptor_data = "\n@protos/perfetto/trace/power/android_entity_state_residency.proto\x12\x0fperfetto.protos\"\xbb\x03\n\x14\x45ntityStateResidency\x12R\n\x12power_entity_state\x18\x01 \x03(\x0b\x32\x36.perfetto.protos.EntityStateResidency.PowerEntityState\x12G\n\tresidency\x18\x02 \x03(\x0b\x32\x34.perfetto.protos.EntityStateResidency.StateResidency\x1a\x66\n\x10PowerEntityState\x12\x14\n\x0c\x65ntity_index\x18\x01 \x01(\x05\x12\x13\n\x0bstate_index\x18\x02 \x01(\x05\x12\x13\n\x0b\x65ntity_name\x18\x03 \x01(\t\x12\x12\n\nstate_name\x18\x04 \x01(\t\x1a\x9d\x01\n\x0eStateResidency\x12\x14\n\x0c\x65ntity_index\x18\x01 \x01(\x05\x12\x13\n\x0bstate_index\x18\x02 \x01(\x05\x12\x1e\n\x16total_time_in_state_ms\x18\x03 \x01(\x04\x12\x1f\n\x17total_state_entry_count\x18\x04 \x01(\x04\x12\x1f\n\x17last_entry_timestamp_ms\x18\x05 \x01(\x04"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    EntityStateResidency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.EntityStateResidency").msgclass
    EntityStateResidency::PowerEntityState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.EntityStateResidency.PowerEntityState").msgclass
    EntityStateResidency::StateResidency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.EntityStateResidency.StateResidency").msgclass
  end
end
