module GraphQL
  class Schema
    class SchemaComparatorChange
      attr_reader :type, :description

      POSSIBLE_TYPES = [
        TYPE_REMOVED = :TYPE_REMOVED,
        TYPE_ADDED = :TYPE_ADDED,
        TYPE_KIND_CHANGED = :TYPE_KIND_CHANGED,
        TYPE_DESCRIPTION_CHANGED = :TYPE_DESCRIPTION_CHANGED,
        ENUM_VALUE_REMOVED = :ENUM_VALUE_REMOVED,
        ENUM_VALUE_ADDED = :ENUM_VALUE_ADDED,
        ENUM_VALUE_DESCRIPTION_CHANGED = :ENUM_VALUE_DESCRIPTION_CHANGED,
        ENUM_VALUE_DEPRECATED = :ENUM_VALUE_DEPRECATED,
        UNION_MEMBER_REMOVED = :UNION_MEMBER_REMOVED,
        UNION_MEMBER_ADDED = :UNION_MEMBER_ADDED,
        DIRECTIVE_REMOVED = :DIRECTIVE_REMOVED,
        DIRECTIVE_ADDED = :DIRECTIVE_ADDED,
        DIRECTIVE_DESCRIPTION_CHANGED = :DIRECTIVE_DESCRIPTION_CHANGED,
        DIRECTIVE_ARGUMENT_DESCRIPTION_CHANGED = :DIRECTIVE_ARGUMENT_DESCRIPTION_CHANGED,
        DIRECTIVE_ARGUMENT_TYPE_CHANGED = :DIRECTIVE_ARGUMENT_TYPE_CHANGED,
        DIRECTIVE_ARGUMENT_DEFAULT_CHANGED = :DIRECTIVE_ARGUMENT_DEFAULT_CHANGED,
        DIRECTIVE_ARGUMENT_REMOVED = :DIRECTIVE_ARGUMENT_REMOVED,
        DIRECTIVE_ARGUMENT_ADDED = :DIRECTIVE_ARGUMENT_ADDED,
        DIRECTIVE_LOCATION_ADDED = :DIRECTIVE_LOCATION_ADDED,
        DIRECTIVE_LOCATION_REMOVED = :DIRECTIVE_LOCATION_REMOVED,
        INPUT_FIELD_REMOVED = :INPUT_FIELD_REMOVED,
        INPUT_FIELD_ADDED = :INPUT_FIELD_ADDED,
        INPUT_FIELD_DESCRIPTION_CHANGED = :INPUT_FIELD_DESCRIPTION_CHANGED,
        INPUT_FIELD_TYPE_CHANGED = :INPUT_FIELD_TYPE_CHANGED,
        INPUT_FIELD_DEFAULT_CHANGED = :INPUT_FIELD_DEFAULT_CHANGED,
        OBJECT_TYPE_INTERFACE_ADDED = :OBJECT_TYPE_INTERFACE_ADDED,
        OBJECT_TYPE_INTERFACE_REMOVED = :OBJECT_TYPE_INTERFACE_REMOVED,
        OBJECT_TYPE_ARGUMENT_ADDED = :OBJECT_TYPE_ARGUMENT_ADDED,
        OBJECT_TYPE_ARGUMENT_TYPE_CHANGED = :OBJECT_TYPE_ARGUMENT_TYPE_CHANGED,
        OBJECT_TYPE_ARGUMENT_DEFAULT_CHANGED = :OBJECT_TYPE_ARGUMENT_DEFAULT_CHANGED,
        OBJECT_TYPE_ARGUMENT_DESCRIPTION_CHANGED = :OBJECT_TYPE_ARGUMENT_DESCRIPTION_CHANGED,
        FIELD_REMOVED = :FIELD_REMOVED,
        FIELD_ADDED = :FIELD_ADDED,
        FIELD_DESCRIPTION_CHANGED = :FIELD_DESCRIPTION_CHANGED,
        FIELD_DEPRECATION_CHANGED = :FIELD_DEPRECATION_CHANGED,
        SCHEMA_QUERY_TYPE_CHANGED = :SCHEMA_QUERY_TYPE_CHANGED,
        SCHEMA_MUTATION_TYPE_CHANGED = :SCHEMA_MUTATION_TYPE_CHANGED,
        SCHEMA_SUBSCRIPTION_TYPE_CHANGED = :SCHEMA_SUBSCRIPTION_TYPE_CHANGED,
      ]

      def initialize(type:, description:, breaking_change:)
        @type = type
        @description = description
        @breaking_change = breaking_change
      end

      def breaking_change?
        @breaking_change
      end
    end
  end
end
