# frozen_string_literal: true
require "base64"

module GraphQL
  class Schema
    module UniqueWithinType
      class << self
        attr_accessor :default_id_separator
      end
      self.default_id_separator = "-"

      module_function

      # **Parameters**
      #
      # - `type_name` (`String`)
      # - `object_value` (`Any`)
      #
      # **Returns**
      #
      # - `String` — a unique, opaque ID generated as a function of the two inputs
      #
      # :call-seq:
      #   encode(String type_name, Any object_value, separator:) -> String
      def encode(type_name, object_value, separator: self.default_id_separator)
        object_value_str = object_value.to_s

        if type_name.include?(separator)
          raise "encode(#{type_name}, #{object_value_str}) contains reserved characters `#{separator}` in the type name"
        end

        Base64.strict_encode64([type_name, object_value_str].join(separator))
      end

      # **Parameters**
      #
      # - `node_id` (`String`) — A unique ID generated by [.encode](rdoc-ref:.encode)
      #
      # **Returns**
      #
      # - `Array<(String, String)>` — The type name & value passed to [.encode](rdoc-ref:.encode)
      #
      # :call-seq:
      #   decode(String node_id, separator:) -> Array[(String, String)]
      def decode(node_id, separator: self.default_id_separator)
        GraphQL::Schema::Base64Encoder.decode(node_id).split(separator, 2)
      end
    end
  end
end
