module GraphQL
  class Schema
    module UniqueWithinType
      DEFAULT_SEPARATOR = "-"

      module_function

      # @param type_name [String]
      # @param object_value [Any]
      # @return [String] a unique, opaque ID generated as a function of the two inputs
      ### Ruby 1.9.3 unofficial support
      # def encode(type_name, object_value, separator: DEFAULT_SEPARATOR)
      def encode(type_name, object_value, options = {})
        separator = options.fetch(:separator, DEFAULT_SEPARATOR)

        object_value_str = object_value.to_s

        if type_name.include?(separator) || object_value_str.include?(separator)
          raise "encode(#{type_name}, #{object_value_str}) contains reserved characters `#{separator}`"
        end

        Base64.strict_encode64([type_name, object_value_str].join(separator))
      end

      # @param node_id [String] A unique ID generated by {.encode}
      # @return [Array<(String, String)>] The type name & value passed to {.encode}
      ### Ruby 1.9.3 unofficial support
      # def decode(node_id, separator: DEFAULT_SEPARATOR)
      def decode(node_id, options = {})
        separator = options.fetch(:separator, DEFAULT_SEPARATOR)

        Base64.decode64(node_id).split(separator)
      end
    end
  end
end
