# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/profiling/deobfuscation.proto

require 'google/protobuf'


descriptor_data = "\n3protos/perfetto/trace/profiling/deobfuscation.proto\x12\x0fperfetto.protos\"F\n\x10ObfuscatedMember\x12\x17\n\x0fobfuscated_name\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65obfuscated_name\x18\x02 \x01(\t\"\xc3\x01\n\x0fObfuscatedClass\x12\x17\n\x0fobfuscated_name\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65obfuscated_name\x18\x02 \x01(\t\x12=\n\x12obfuscated_members\x18\x03 \x03(\x0b\x32!.perfetto.protos.ObfuscatedMember\x12=\n\x12obfuscated_methods\x18\x04 \x03(\x0b\x32!.perfetto.protos.ObfuscatedMember\"\x80\x01\n\x14\x44\x65obfuscationMapping\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x14\n\x0cversion_code\x18\x02 \x01(\x03\x12<\n\x12obfuscated_classes\x18\x03 \x03(\x0b\x32 .perfetto.protos.ObfuscatedClass"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    ObfuscatedMember = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.ObfuscatedMember").msgclass
    ObfuscatedClass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.ObfuscatedClass").msgclass
    DeobfuscationMapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.DeobfuscationMapping").msgclass
  end
end
