#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'



module GraphQL
  module Language
    class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 208)

def initialize(query_string)
  @query_string = query_string
end

def parse_document
  @document ||= begin
    @tokens ||= GraphQL::Language::Lexer.tokenize(@query_string)
    if @tokens.none?
      make_node(:Document, definitions: [])
    else
      do_parse
    end
  end
end

def self.parse(query_string)
  self.new(query_string).parse_document
end

private

def next_token
  lexer_token = @tokens.shift
  if lexer_token.nil?
    nil
  else
    [lexer_token.name, lexer_token]
  end
end

def on_error(parser_token_id, lexer_token, vstack)
  if lexer_token == "$"
    raise GraphQL::ParseError.new("Unexpected end of document", nil, nil, @query_string)
  else
    parser_token_name = token_to_str(parser_token_id)
    line, col = lexer_token.line_and_column
    raise GraphQL::ParseError.new("Parse error on #{lexer_token.to_s.inspect} (#{parser_token_name}) at [#{line}, #{col}]", line, col, @query_string)
  end
end

def make_node(node_name, assigns)
  assigns.each do |key, value|
    if key != :position_source && value.is_a?(GraphQL::Language::Token)
      assigns[key] = value.to_s
    end
  end

  GraphQL::Language::Nodes.const_get(node_name).new(assigns)
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    83,    35,   102,    84,    34,   103,    85,   102,    86,   111,
    77,    78,    39,    74,    75,    76,    83,    59,    46,    84,
    67,    39,    85,    35,    86,    42,    77,    78,    71,    74,
    75,    76,    83,    39,    35,    84,     9,     9,    85,    30,
    86,     9,    77,    78,     9,    74,    75,    76,    83,    28,
    39,    84,   105,     9,    85,     9,    86,    39,    77,    78,
    39,    74,    75,    76,    83,   109,    15,    84,    94,    39,
    85,    65,    86,    46,    77,    78,   nil,    74,    75,    76,
    10,    19,    12,    13,    14,    31,    10,    19,    12,    13,
    14,    91,   nil,   nil,   nil,    26,    10,    19,    12,    13,
    14,    10,    19,    12,    13,    14,    91,   nil,   nil,   nil,
    26,    10,    19,    12,    13,    14,    10,    19,    12,    13,
    36,   nil,   nil,     9,    39,    10,    11,    12,    13,    14,
     9,   nil,    10,    11,    12,    13,    14,   107,    10,    19,
    12,    13,    14,    97,    10,    19,    12,    13,    14,    10,
    19,    12,    13,    14,    10,    19,    12,    13,    14,    10,
    19,    12,    13,    14,    10,    19,    12,    13,    14,    10,
    19,    12,    13,    14,    10,    19,    12,    13,    14,    10,
    19,    12,    13,    14,    10,    19,    12,    13,    14,    10,
    19,    12,    13,    14 ]

racc_action_check = [
   109,    25,    89,   109,    25,    89,   109,   104,   109,   104,
   109,   109,    57,   109,   109,   109,   103,    44,    44,   103,
    51,    52,   103,    54,   103,    27,   103,   103,    61,   103,
   103,   103,    67,    64,    48,    67,    68,    70,    67,    17,
    67,    72,    67,    67,    47,    67,    67,    67,    95,    15,
    29,    95,    95,    43,    95,    41,    95,    40,    95,    95,
    37,    95,    95,    95,    84,   100,     1,    84,    84,    33,
    84,    49,    84,    30,    84,    84,   nil,    84,    84,    84,
    49,    49,    49,    49,    49,    20,    20,    20,    20,    20,
    20,    71,   nil,   nil,   nil,    20,    71,    71,    71,    71,
    71,     9,     9,     9,     9,     9,    91,   nil,   nil,   nil,
     9,    91,    91,    91,    91,    91,    26,    26,    26,    26,
    26,   nil,   nil,     3,    26,     3,     3,     3,     3,     3,
     0,   nil,     0,     0,     0,     0,     0,    98,    98,    98,
    98,    98,    98,    85,    85,    85,    85,    85,    85,    46,
    46,    46,    46,    46,    35,    35,    35,    35,    35,    36,
    36,    36,    36,    36,    34,    34,    34,    34,    34,    39,
    39,    39,    39,    39,    83,    83,    83,    83,    83,    11,
    11,    11,    11,    11,    42,    42,    42,    42,    42,     7,
     7,     7,     7,     7 ]

racc_action_pointer = [
   120,    66,   nil,   113,   nil,   nil,   nil,   177,   nil,    89,
   nil,   167,   nil,   nil,   nil,    49,   nil,    37,   nil,   nil,
    74,   nil,   nil,   nil,   nil,    -1,   104,     9,   nil,    30,
    69,   nil,   nil,    49,   152,   142,   147,    40,   nil,   157,
    37,    45,   172,    43,    14,   nil,   137,    34,    32,    68,
   nil,    15,     1,   nil,    21,   nil,   nil,    -8,   nil,   nil,
   nil,    23,   nil,   nil,    13,   nil,   nil,    28,    26,   nil,
    27,    84,    31,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   162,    60,   132,   nil,   nil,   nil,    -4,
   nil,    99,   nil,   nil,   nil,    44,   nil,   nil,   126,   nil,
    60,   nil,   nil,    12,     1,   nil,   nil,   nil,   nil,    -4,
   nil,   nil,   nil ]

racc_action_default = [
   -70,   -70,    -1,    -2,    -3,    -5,    -6,    -9,    -8,   -70,
   -31,   -32,   -33,   -34,   -35,   -70,    -4,   -11,   -10,   -32,
   -70,   -24,   -26,   -27,   -28,   -36,   -61,   -70,   113,   -61,
   -70,   -21,   -25,   -61,   -70,   -70,   -35,   -62,   -63,   -70,
   -61,   -70,   -70,   -70,   -70,   -13,   -70,   -22,   -36,   -70,
   -38,   -70,   -61,   -64,   -36,   -66,   -68,   -61,    -7,   -12,
   -14,   -70,   -23,   -29,   -61,   -37,   -39,   -70,   -70,   -65,
   -70,   -70,   -22,   -40,   -41,   -42,   -43,   -44,   -45,   -46,
   -47,   -48,   -49,   -70,   -70,   -70,   -60,   -67,   -69,   -19,
   -16,   -70,   -30,   -50,   -51,   -70,   -53,   -55,   -70,   -57,
   -70,   -15,   -17,   -70,   -70,   -52,   -54,   -56,   -58,   -70,
   -20,   -18,   -59 ]

racc_goto_table = [
    18,    63,    25,    89,    27,    73,   101,    21,    44,    56,
    20,    58,    99,    25,    29,    62,    45,    41,    32,    40,
    43,    33,    96,   104,    47,   108,    92,    48,    51,    52,
    60,    55,    54,   106,    17,    57,    87,    50,    88,    61,
    62,   110,    51,    68,    64,     1,     4,   112,    70,    16,
    69,    66,    49,     3,    95,    72,    98,     2,    53,   nil,
   nil,   nil,   nil,   nil,    90,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    93,   nil,   100,   nil,
   nil,   nil,   nil,   nil,    90,   nil,   nil,   nil,   nil,   nil,
   nil,   100 ]

racc_goto_check = [
     7,    18,     7,    14,     7,    16,    15,    19,    12,    11,
    17,    11,    32,     7,     9,    11,    13,    10,    19,     7,
    10,    23,    16,    14,    10,    32,    18,     7,     7,     7,
    13,    10,     7,    16,     8,     7,    11,    25,    11,     7,
    11,    16,     7,    10,    23,     1,     4,    16,    10,     4,
    23,    25,    24,     3,    30,    10,    31,     2,    34,   nil,
   nil,   nil,   nil,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     7,   nil,     7,   nil,
   nil,   nil,   nil,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,     7 ]

racc_goto_pointer = [
   nil,    45,    57,    53,    46,   nil,   nil,    -7,    27,    -3,
    -9,   -32,   -22,   -14,   -68,   -83,   -62,     1,   -46,    -2,
   nil,   nil,   nil,    -4,    17,     2,   nil,   nil,   nil,   nil,
   -30,   -29,   -73,   nil,    21 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     5,     6,     7,   nil,   nil,
   nil,     8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    22,    23,    24,   nil,   nil,   nil,    79,    80,    81,    82,
   nil,   nil,   nil,    37,    38 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 23, :_reduce_none,
  1, 24, :_reduce_2,
  1, 25, :_reduce_3,
  2, 25, :_reduce_4,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  5, 27, :_reduce_7,
  1, 27, :_reduce_8,
  0, 30, :_reduce_9,
  1, 30, :_reduce_none,
  0, 31, :_reduce_11,
  3, 31, :_reduce_12,
  1, 34, :_reduce_13,
  2, 34, :_reduce_14,
  5, 35, :_reduce_15,
  1, 36, :_reduce_16,
  2, 36, :_reduce_17,
  3, 36, :_reduce_18,
  0, 37, :_reduce_19,
  2, 37, :_reduce_20,
  3, 33, :_reduce_21,
  0, 40, :_reduce_22,
  1, 40, :_reduce_23,
  1, 39, :_reduce_24,
  2, 39, :_reduce_25,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  4, 42, :_reduce_29,
  6, 42, :_reduce_30,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  0, 45, :_reduce_36,
  3, 45, :_reduce_37,
  1, 46, :_reduce_38,
  2, 46, :_reduce_39,
  3, 47, :_reduce_40,
  1, 38, :_reduce_41,
  1, 38, :_reduce_42,
  1, 38, :_reduce_43,
  1, 38, :_reduce_44,
  1, 38, :_reduce_45,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  2, 48, :_reduce_50,
  2, 49, :_reduce_51,
  3, 49, :_reduce_52,
  1, 52, :_reduce_53,
  2, 52, :_reduce_54,
  2, 50, :_reduce_55,
  3, 50, :_reduce_56,
  1, 53, :_reduce_57,
  2, 53, :_reduce_58,
  3, 54, :_reduce_59,
  1, 51, :_reduce_60,
  0, 32, :_reduce_61,
  1, 32, :_reduce_none,
  1, 55, :_reduce_63,
  2, 55, :_reduce_64,
  3, 56, :_reduce_65,
  3, 43, :_reduce_66,
  5, 44, :_reduce_67,
  3, 44, :_reduce_68,
  6, 28, :_reduce_69 ]

racc_reduce_n = 70

racc_shift_n = 113

racc_token_table = {
  false => 0,
  :error => 1,
  :RPAREN => 2,
  :LPAREN => 3,
  :VAR_SIGN => 4,
  :COLON => 5,
  :BANG => 6,
  :RBRACKET => 7,
  :LBRACKET => 8,
  :EQUALS => 9,
  :RCURLY => 10,
  :LCURLY => 11,
  :IDENTIFIER => 12,
  :FRAGMENT => 13,
  :TRUE => 14,
  :FALSE => 15,
  :ON => 16,
  :FLOAT => 17,
  :INT => 18,
  :STRING => 19,
  :DIR_SIGN => 20,
  :ELLIPSIS => 21 }

racc_nt_base = 22

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "RPAREN",
  "LPAREN",
  "VAR_SIGN",
  "COLON",
  "BANG",
  "RBRACKET",
  "LBRACKET",
  "EQUALS",
  "RCURLY",
  "LCURLY",
  "IDENTIFIER",
  "FRAGMENT",
  "TRUE",
  "FALSE",
  "ON",
  "FLOAT",
  "INT",
  "STRING",
  "DIR_SIGN",
  "ELLIPSIS",
  "$start",
  "target",
  "document",
  "definitions_list",
  "definition",
  "operation_definition",
  "fragment_definition",
  "name",
  "operation_name_opt",
  "variable_definitions_opt",
  "directives_list_opt",
  "selection_set",
  "variable_definitions_list",
  "variable_definition",
  "variable_definition_type_name",
  "variable_definition_default_value_opt",
  "input_value",
  "selection_list",
  "selection_set_opt",
  "selection",
  "field",
  "fragment_spread",
  "inline_fragment",
  "arguments_opt",
  "arguments_list",
  "argument",
  "variable",
  "list_value",
  "object_value",
  "enum_value",
  "list_value_list",
  "object_value_list",
  "object_value_field",
  "directives_list",
  "directive" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'parser.y', 4)
  def _reduce_2(val, _values, result)
     return make_node(:Document, definitions: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_3(val, _values, result)
     return [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 8)
  def _reduce_4(val, _values, result)
     val[0] << val[1] 
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_7(val, _values, result)
            return  make_node(
          :OperationDefinition, {
            operation_type: val[0],
            name:           val[1],
            variables:      val[2],
            directives:     val[3],
            selections:     val[4],
            position_source: val[0],
          }
        )
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_8(val, _values, result)
            return make_node(
          :OperationDefinition, {
            operation_type: "query",
            selections: val[0],
          }
        )
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_9(val, _values, result)
     return nil 
    result
  end
.,.,

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.y', 41)
  def _reduce_11(val, _values, result)
     return [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_12(val, _values, result)
     return val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 45)
  def _reduce_13(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 46)
  def _reduce_14(val, _values, result)
     val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_15(val, _values, result)
            return make_node(:VariableDefinition, {
          name: val[1],
          type: val[3],
          default_value: val[4],
          position_source: val[0],
        })
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_16(val, _values, result)
     return make_node(:TypeName, name: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_17(val, _values, result)
     return make_node(:NonNullType, of_type: val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_18(val, _values, result)
     return make_node(:ListType, of_type: val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_19(val, _values, result)
     return nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_20(val, _values, result)
     return val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_21(val, _values, result)
     return val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_22(val, _values, result)
     return [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_23(val, _values, result)
     return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_24(val, _values, result)
     return [result] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_25(val, _values, result)
     val[0] << val[1] 
    result
  end
.,.,

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_29(val, _values, result)
                return make_node(
              :Field, {
                name:         val[0],
                arguments:    val[1],
                directives:   val[2],
                selections:   val[3],
                position_source: val[0],
              }
            )
          
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_30(val, _values, result)
                return make_node(
              :Field, {
                alias:        val[0],
                name:         val[2],
                arguments:    val[3],
                directives:   val[4],
                selections:   val[5],
                position_source: val[0],
              }
            )
          
    result
  end
.,.,

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_36(val, _values, result)
     return [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_37(val, _values, result)
     return val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 119)
  def _reduce_38(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_39(val, _values, result)
     val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_40(val, _values, result)
     return make_node(:Argument, name: val[0], value: val[2], position_source: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 126)
  def _reduce_41(val, _values, result)
     return val[0].to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 127)
  def _reduce_42(val, _values, result)
     return val[0].to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 128)
  def _reduce_43(val, _values, result)
     return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 129)
  def _reduce_44(val, _values, result)
     return true 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 130)
  def _reduce_45(val, _values, result)
     return false 
    result
  end
.,.,

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'parser.y', 136)
  def _reduce_50(val, _values, result)
     return make_node(:VariableIdentifier, name: val[1], position_source: val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 139)
  def _reduce_51(val, _values, result)
     return [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 140)
  def _reduce_52(val, _values, result)
     return val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 143)
  def _reduce_53(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 144)
  def _reduce_54(val, _values, result)
     val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 147)
  def _reduce_55(val, _values, result)
     return make_node(:InputObject, arguments: [], position_source: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 148)
  def _reduce_56(val, _values, result)
     return make_node(:InputObject, arguments: val[1], position_source: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 151)
  def _reduce_57(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 152)
  def _reduce_58(val, _values, result)
     val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 155)
  def _reduce_59(val, _values, result)
     return make_node(:Argument, name: val[0], value: val[2], position_source: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 157)
  def _reduce_60(val, _values, result)
     return make_node(:Enum, name: val[0], position_source: val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 160)
  def _reduce_61(val, _values, result)
     return [] 
    result
  end
.,.,

# reduce 62 omitted

module_eval(<<'.,.,', 'parser.y', 164)
  def _reduce_63(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 165)
  def _reduce_64(val, _values, result)
     val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_65(val, _values, result)
     return make_node(:Directive, name: val[1], arguments: val[2], position_source: val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 170)
  def _reduce_66(val, _values, result)
     return make_node(:FragmentSpread, name: val[1], directives: val[2], position_source: val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 174)
  def _reduce_67(val, _values, result)
            return make_node(:InlineFragment, {
          type: val[2],
          directives: val[3],
          selections: val[4],
          position_source: val[0]
        })
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 182)
  def _reduce_68(val, _values, result)
            return make_node(:InlineFragment, {
          type: nil,
          directives: val[1],
          selections: val[2],
          position_source: val[0]
        })
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 192)
  def _reduce_69(val, _values, result)
          return make_node(:FragmentDefinition, {
          name:       val[1],
          type:       val[3],
          directives: val[4],
          selections: val[5],
          position_source: val[0],
        }
      )
    
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
    end   # module Language
  end   # module GraphQL
