# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/android/graphics/point.proto

require 'google/protobuf'


descriptor_data = "\n2protos/perfetto/trace/android/graphics/point.proto\x12\x0fperfetto.protos\"\"\n\nPointProto\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    PointProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.PointProto").msgclass
  end
end
