# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/ui_state.proto

require 'google/protobuf'


descriptor_data = "\n$protos/perfetto/trace/ui_state.proto\x12\x0fperfetto.protos\"\xc5\x01\n\x07UiState\x12\x19\n\x11timeline_start_ts\x18\x01 \x01(\x03\x12\x17\n\x0ftimeline_end_ts\x18\x02 \x01(\x03\x12\x44\n\x11highlight_process\x18\x03 \x01(\x0b\x32).perfetto.protos.UiState.HighlightProcess\x1a@\n\x10HighlightProcess\x12\r\n\x03pid\x18\x01 \x01(\rH\x00\x12\x11\n\x07\x63mdline\x18\x02 \x01(\tH\x00\x42\n\n\x08selector"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    UiState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.UiState").msgclass
    UiState::HighlightProcess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.UiState.HighlightProcess").msgclass
  end
end
