# frozen_string_literal: true
source 'https://rubygems.org'

gem 'rails', '~> 5.2.1'
gem 'puma'
gem 'capybara', '3.34.0'
gem 'selenium-webdriver'
gem 'graphql', path: File.expand_path('../../', __dir__)

group :development do
  gem 'listen'
end

gem "webdrivers", "~> 4.1"
