# frozen_string_literal: true
source 'https://rubygems.org'

gem 'bootsnap'
gem 'rails', '~> 6.1'
gem 'puma'
gem 'capybara'
gem 'selenium-webdriver', "4.11.0"
gem 'graphql', path: File.expand_path('../../', __dir__)
gem "rexml"

group :development do
  gem 'listen'
end

gem "webdrivers", "~> 4.1"
