# frozen_string_literal: true
source 'https://rubygems.org'

gem 'bootsnap'
gem 'rails', '~>7.0'
gem 'sprockets-rails'
gem 'puma'
gem 'capybara'
gem 'selenium-webdriver'
gem 'graphql', path: File.expand_path('../../', __dir__)

gem "listen", group: :development
