# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/android/view/insetsanimationcontrolimpl.proto

require 'google/protobuf'


descriptor_data = "\nCprotos/perfetto/trace/android/view/insetsanimationcontrolimpl.proto\x12\x0fperfetto.protos\"\xd9\x01\n\x1fInsetsAnimationControlImplProto\x12\x14\n\x0cis_cancelled\x18\x01 \x01(\x08\x12\x13\n\x0bis_finished\x18\x02 \x01(\x08\x12\x12\n\ntmp_matrix\x18\x03 \x01(\t\x12\x16\n\x0epending_insets\x18\x04 \x01(\t\x12\x18\n\x10pending_fraction\x18\x05 \x01(\x02\x12\x17\n\x0fshown_on_finish\x18\x06 \x01(\x08\x12\x15\n\rcurrent_alpha\x18\x07 \x01(\x02\x12\x15\n\rpending_alpha\x18\x08 \x01(\x02"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    InsetsAnimationControlImplProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.InsetsAnimationControlImplProto").msgclass
  end
end
