# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/android/server/animationadapter.proto

require 'google/protobuf'

require 'protos/perfetto/trace/android/graphics/point_pb'
require 'protos/perfetto/trace/android/view/remote_animation_target_pb'


descriptor_data = "\n;protos/perfetto/trace/android/server/animationadapter.proto\x12\x0fperfetto.protos\x1a\x32protos/perfetto/trace/android/graphics/point.proto\x1a@protos/perfetto/trace/android/view/remote_animation_target.proto\"\x98\x01\n\x15\x41nimationAdapterProto\x12:\n\x05local\x18\x01 \x01(\x0b\x32+.perfetto.protos.LocalAnimationAdapterProto\x12\x43\n\x06remote\x18\x02 \x01(\x0b\x32\x33.perfetto.protos.RemoteAnimationAdapterWrapperProto\"a\n\"RemoteAnimationAdapterWrapperProto\x12;\n\x06target\x18\x01 \x01(\x0b\x32+.perfetto.protos.RemoteAnimationTargetProto\"Y\n\x1aLocalAnimationAdapterProto\x12;\n\x0e\x61nimation_spec\x18\x01 \x01(\x0b\x32#.perfetto.protos.AnimationSpecProto\"\xfc\x01\n\x12\x41nimationSpecProto\x12\x39\n\x06window\x18\x01 \x01(\x0b\x32).perfetto.protos.WindowAnimationSpecProto\x12\x35\n\x04move\x18\x02 \x01(\x0b\x32\'.perfetto.protos.MoveAnimationSpecProto\x12\x37\n\x05\x61lpha\x18\x03 \x01(\x0b\x32(.perfetto.protos.AlphaAnimationSpecProto\x12;\n\x06rotate\x18\x04 \x01(\x0b\x32+.perfetto.protos.RotationAnimationSpecProto\"-\n\x18WindowAnimationSpecProto\x12\x11\n\tanimation\x18\x01 \x01(\t\"\x81\x01\n\x16MoveAnimationSpecProto\x12)\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x1b.perfetto.protos.PointProto\x12\'\n\x02to\x18\x02 \x01(\x0b\x32\x1b.perfetto.protos.PointProto\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\"H\n\x17\x41lphaAnimationSpecProto\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x02\x12\n\n\x02to\x18\x02 \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\"W\n\x1aRotationAnimationSpecProto\x12\x12\n\nstart_luma\x18\x01 \x01(\x02\x12\x10\n\x08\x65nd_luma\x18\x02 \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AnimationAdapterProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AnimationAdapterProto").msgclass
    RemoteAnimationAdapterWrapperProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.RemoteAnimationAdapterWrapperProto").msgclass
    LocalAnimationAdapterProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.LocalAnimationAdapterProto").msgclass
    AnimationSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AnimationSpecProto").msgclass
    WindowAnimationSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.WindowAnimationSpecProto").msgclass
    MoveAnimationSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.MoveAnimationSpecProto").msgclass
    AlphaAnimationSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AlphaAnimationSpecProto").msgclass
    RotationAnimationSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.RotationAnimationSpecProto").msgclass
  end
end
