# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/android/server/windowcontainerthumbnail.proto

require 'google/protobuf'

require 'protos/perfetto/trace/android/server/surfaceanimator_pb'


descriptor_data = "\nCprotos/perfetto/trace/android/server/windowcontainerthumbnail.proto\x12\x0fperfetto.protos\x1a:protos/perfetto/trace/android/server/surfaceanimator.proto\"\x7f\n\x1dWindowContainerThumbnailProto\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12?\n\x10surface_animator\x18\x03 \x01(\x0b\x32%.perfetto.protos.SurfaceAnimatorProto"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    WindowContainerThumbnailProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.WindowContainerThumbnailProto").msgclass
  end
end
