# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/android/android_game_intervention_list.proto

require 'google/protobuf'


descriptor_data = "\nBprotos/perfetto/trace/android/android_game_intervention_list.proto\x12\x0fperfetto.protos\"\x8f\x03\n\x1b\x41ndroidGameInterventionList\x12S\n\rgame_packages\x18\x01 \x03(\x0b\x32<.perfetto.protos.AndroidGameInterventionList.GamePackageInfo\x12\x13\n\x0bparse_error\x18\x02 \x01(\x08\x12\x12\n\nread_error\x18\x03 \x01(\x08\x1aZ\n\x0cGameModeInfo\x12\x0c\n\x04mode\x18\x01 \x01(\r\x12\x11\n\tuse_angle\x18\x02 \x01(\x08\x12\x1c\n\x14resolution_downscale\x18\x03 \x01(\x02\x12\x0b\n\x03\x66ps\x18\x04 \x01(\x02\x1a\x95\x01\n\x0fGamePackageInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\x04\x12\x14\n\x0c\x63urrent_mode\x18\x03 \x01(\r\x12Q\n\x0egame_mode_info\x18\x04 \x03(\x0b\x32\x39.perfetto.protos.AndroidGameInterventionList.GameModeInfo"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Perfetto
  module Protos
    AndroidGameInterventionList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidGameInterventionList").msgclass
    AndroidGameInterventionList::GameModeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidGameInterventionList.GameModeInfo").msgclass
    AndroidGameInterventionList::GamePackageInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("perfetto.protos.AndroidGameInterventionList.GamePackageInfo").msgclass
  end
end
